/* The two committed, served-as-is files that decide whether Google may index a
   shop site at all: public/_headers and public/robots.txt.

   These are NOT regenerated by the shop build — they ship exactly as committed.
   But `PLATFORM_BUILD=1 npm run build` (the Lumin owner console) deliberately
   overwrites both with noindex / Disallow-all, because the admin console must
   stay out of search. Both builds write into the same public/ directory, so
   running the platform build locally silently rewrites the shop files, and a
   `git add -A` then commits a site-wide noindex to every shop.

   That happened once (commit ddc4745) and would have deindexed all three live
   shops. These tests are the tripwire. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (p) => readFileSync(new URL('../' + p, import.meta.url), 'utf8');

test('public/_headers lets search engines index the shop sites', () => {
  const h = read('public/_headers');
  assert.match(h, /X-Robots-Tag:\s*index,\s*follow/,
    'public/_headers must allow indexing — did a PLATFORM_BUILD=1 run overwrite it?');
  assert.doesNotMatch(h.split('/api/')[0], /noindex/,
    'the site-wide (/*) rule must not contain noindex');
});

test('public/robots.txt allows crawling, and keeps private paths out', () => {
  const r = read('public/robots.txt');
  assert.match(r, /^\s*Allow:\s*\/\s*$/m,
    'robots.txt must Allow: / — did a PLATFORM_BUILD=1 run overwrite it?');
  assert.doesNotMatch(r, /^\s*Disallow:\s*\/\s*$/m,
    'robots.txt must not Disallow the whole site');
  // The paths that should stay unindexed.
  for (const p of ['/api/', '/staff/', '/thank-you']) {
    assert.ok(r.includes('Disallow: ' + p), `robots.txt should disallow ${p}`);
  }
});
