/* Dominic's kebabs and wraps open on Salad + Garlic Yogurt, on the TILL ONLY.
   Run: node --import ./tests/support/register.mjs --test tests/

   OWNER'S DECISION, 19 Sep 2026. The risk this pins is quiet loss, not money:
   the menu files are generated by tools/_gen-dominic-menu.py from a workbook
   that is NOT in the repo, so the rule table in that script is the only record
   of the decision. A re-run against a script that has lost the rule rewrites
   both files and the defaults simply stop being there — no error, no failed
   build, just staff back to tapping Salad and a sauce on every kebab.

   The website half is the same decision: Sauce is the first default that
   expresses a PREFERENCE (Garlic Yogurt is one of ten, all £0.00, including
   "No Sauce"). Staff read an order back and correct it; a customer who wanted
   chilli sauce and did not notice a pre-filled dropdown just gets the wrong
   food. So posDefault, never default. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const VISUAL = JSON.parse(readFileSync(
  new URL('../data/shops/dominic-pizza/menu-visual.json', import.meta.url), 'utf8'));

const WANT = { salad: 'Salad', sauce: 'Garlic Yogurt' };

/* Every (item, group) in Kebabs and Wraps whose label we have a rule for. */
function targets() {
  const out = [];
  for (const cat of VISUAL) {
    if (!/^(kebabs|wraps)$/i.test(cat.name)) continue;
    for (const item of cat.items || []) {
      for (const g of item.options || []) {
        const want = WANT[String(g.label || '').toLowerCase()];
        if (want) out.push({ cat: cat.name, item, group: g, want });
      }
    }
  }
  return out;
}

test('the groups this covers still exist', () => {
  // 5 kebabs x (salad+sauce) + 6 wraps x salad + 5 wraps x sauce = 21.
  // Donner Hoagie Wrap carries no Sauce group at all in the shop's workbook.
  assert.equal(targets().length, 21);
});

test('salad and garlic yogurt are pre-selected on the till', () => {
  const missing = targets()
    .filter(({ group, want }) =>
      !(group.choices || []).some((c) => c.label === want && c.posDefault === true))
    .map(({ cat, item, group, want }) => `${cat} · ${item.name} · ${group.label} → ${want}`);
  assert.deepEqual(missing, [], 'not defaulted on the till:\n  ' + missing.join('\n  '));
});

test('nothing is pre-selected on the WEBSITE', () => {
  // `default` is the both-surfaces flag. These groups must not carry it.
  const leaked = targets()
    .flatMap(({ cat, item, group }) => (group.choices || [])
      .filter((c) => c.default === true)
      .map((c) => `${cat} · ${item.name} · ${group.label} · ${c.label}`));
  assert.deepEqual(leaked, [], 'these would pre-select for CUSTOMERS too:\n  ' + leaked.join('\n  '));
});

test('exactly one choice per group is defaulted', () => {
  // Two posDefaults in one single-select is ambiguous — the till takes the
  // first it finds, so which one wins depends on choice order.
  for (const { cat, item, group } of targets()) {
    const n = (group.choices || []).filter((c) => c.posDefault === true).length;
    assert.equal(n, 1, `${cat} · ${item.name} · ${group.label} has ${n} defaults`);
  }
});
