/* Prints the JSON that GET /api/config would return for the currently-built
   shop, so the design loop can screenshot the landing page without a backend.

   It is generated by calling the REAL functions the endpoint calls
   (getPublicConfig / isOpenNow / listSlots) rather than by hand-writing a
   plausible object. A hand-written stub is how a screenshot ends up showing an
   "open" shop that the live site renders as closed, and then the whole loop
   optimises against a page that does not exist.

   Needs the repo's JSON import loader (functions/_lib/config.js imports
   data/_active/config.json). render.mjs runs this as:
     node --import tests/support/register.mjs tools/design-loop/api-stub.mjs
*/
import { getPublicConfig, getConfig } from '../../functions/_lib/config.js';
import { isOpenNow, listSlots } from '../../functions/_lib/hours.js';

const cfg = getPublicConfig();
const full = getConfig();

process.stdout.write(JSON.stringify({
  ...cfg,
  closure: cfg.closure || null,
  // No Stripe keys in a local render — the landing page never needs them, and
  // baking a real key into a dev tool would be a way to leak one.
  stripe: { publishableKey: null, connectedAccountId: full.stripe?.connectedAccountId || null },
  addressLookup: { enabled: false },
  staffLogin: { passwordMode: false },
  isOpenNow: isOpenNow(full),
  slots: listSlots(full),
}));
