/* gen-shop.mjs — generate this shop's app identity (the app-layer mirror of
   scripts/build-shop.js). Reads SHOP_SLUG, loads the shop's config.json, and
   writes everything per-shop the Capacitor project needs:

     capacitor.config.json   from capacitor.config.template.json ({{tokens}})
     gen/app-base.js         baked API base + slug + scheme, loaded FIRST in the app
     gen/build-meta.json     slug + domain, cross-checked by sync-web.mjs
     assets/icon.png         from data/shops/<slug>/app/icon.png (fallbacks below)
     assets/splash.png       from data/shops/<slug>/app/splash.png (optional)
     gen/google-services.json + gen/GoogleService-Info.plist  (Firebase, optional —
                             placed into the native projects by patch-android/patch-ios)

   Everything written is gitignored. Run from app-customer/ via `npm run gen`
   (SHOP_SLUG=<slug> npm run gen). */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));   // app-customer/scripts
const appDir = resolve(here, '..');                      // app-customer
const repoRoot = resolve(appDir, '..');                  // repo root

const rawSlug = (process.env.SHOP_SLUG || '').trim();
if (!rawSlug && (process.env.CF_PAGES || process.env.CI)) {
  console.warn('⚠️  gen-shop: SHOP_SLUG is not set in CI — defaulting to "ricos".');
}
const slug = rawSlug || 'ricos';
const shopDir = resolve(repoRoot, 'data', 'shops', slug);

if (slug.startsWith('_') || !/^[a-z0-9-]+$/.test(slug)) {
  console.error(`✗ gen-shop: invalid shop slug "${slug}".`);
  process.exit(1);
}
if (!existsSync(shopDir)) {
  console.error(`✗ gen-shop: no shop folder at data/shops/${slug}.`);
  process.exit(1);
}

const config = JSON.parse(readFileSync(resolve(shopDir, 'config.json'), 'utf8'));
const app = config.app || {};

if (!app.enabled) {
  console.error(`✗ gen-shop: shop "${slug}" has no enabled app block in its config.json.`);
  console.error('  Add/enable the "app" block (see data/shops/_template/config.json and docs/ADDING_A_SHOP_APP.md).');
  process.exit(1);
}
if (!/^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(app.appId || '')) {
  console.error(`✗ gen-shop: app.appId "${app.appId}" is not a valid reverse-DNS bundle id.`);
  process.exit(1);
}
const domain = (config.business?.domain || '').trim();
if (!domain || /TODO|REPLACE/i.test(domain)) {
  console.error(`✗ gen-shop: business.domain ("${domain}") must be the shop's live apex domain — it becomes the app's baked API base.`);
  process.exit(1);
}

// The baked backend origin. MUST be the exact canonical apex: public/_redirects
// 301s www/.com variants, and a 301 breaks API POSTs (same rule as the till's
// provisioning DIRECTORY in app/web/provision.js).
const base = `https://${domain}`;

// capacitor.config.json from the template.
const tokens = {
  appId: app.appId,
  appName: app.appName || config.business?.shortName || config.business?.tradingName || slug,
  bgColor: config.theme?.background || '#ffffff',
};
let tpl = readFileSync(resolve(appDir, 'capacitor.config.template.json'), 'utf8');
tpl = tpl.replace(/\{\{(\w+)\}\}/g, (_m, k) => {
  if (!(k in tokens)) {
    console.error(`✗ gen-shop: template token {{${k}}} has no value.`);
    process.exit(1);
  }
  return tokens[k];
});
const capCfg = JSON.parse(tpl);
delete capCfg._comment;
writeFileSync(resolve(appDir, 'capacitor.config.json'), JSON.stringify(capCfg, null, 2) + '\n');
console.log(`✓ gen-shop: capacitor.config.json (${app.appId} · "${tokens.appName}")`);

// gen/app-base.js — the baked per-shop constants, loaded before native.js.
mkdirSync(resolve(appDir, 'gen'), { recursive: true });
const appBase = {
  base,
  slug,
  scheme: app.deepLinkScheme || '',
  shortName: config.business?.shortName || config.business?.tradingName || slug,
};
writeFileSync(resolve(appDir, 'gen', 'app-base.js'),
  `/* Generated by gen-shop.mjs for shop "${slug}" — do not edit. */\n` +
  `window.LUMIN_APP_CONFIG = ${JSON.stringify(appBase, null, 2)};\n`);
writeFileSync(resolve(appDir, 'gen', 'build-meta.json'), JSON.stringify({ slug, domain }, null, 2) + '\n');
console.log(`✓ gen-shop: gen/app-base.js (base ${base})`);

// App icon: prefer a dedicated store icon (1024×1024) in the shop's app/
// folder, fall back to the shop's square favicon, then the logo (which may
// letterbox — the runbook tells shops to supply a real icon).
mkdirSync(resolve(appDir, 'assets'), { recursive: true });
const iconCandidates = [
  resolve(shopDir, 'app', 'icon.png'),
  resolve(shopDir, 'icon.png'),
  resolve(shopDir, 'logo.png'),
];
const icon = iconCandidates.find(existsSync);
if (!icon) {
  console.error(`✗ gen-shop: no icon found for "${slug}" (looked for app/icon.png, icon.png, logo.png).`);
  process.exit(1);
}
copyFileSync(icon, resolve(appDir, 'assets', 'icon.png'));
console.log(`✓ gen-shop: assets/icon.png (from ${icon.replace(repoRoot + '/', '')})`);
const splash = resolve(shopDir, 'app', 'splash.png');
if (existsSync(splash)) {
  copyFileSync(splash, resolve(appDir, 'assets', 'splash.png'));
  console.log('✓ gen-shop: assets/splash.png');
}

// Firebase registration files (push). Optional — the app builds and runs
// without them; push registration just fails gracefully.
let firebase = 0;
for (const f of ['google-services.json', 'GoogleService-Info.plist']) {
  const src = resolve(shopDir, 'app', f);
  if (existsSync(src)) { copyFileSync(src, resolve(appDir, 'gen', f)); firebase++; console.log(`✓ gen-shop: gen/${f}`); }
}
if (!firebase) {
  console.warn(`⚠️  gen-shop: no Firebase files under data/shops/${slug}/app/ — push notifications will be OFF in this build.`);
}

console.log(`gen-shop: shop "${slug}" ready — next: npm run sync-web`);
